### ISSUE TITLE
Re-ranking network

### ISSUE THREAD

**Issue by yejy53** [ShihaoShao-GH/SuperGlobal#12]
Thank you for your great work! I am very interested in your re-ranking network. It seems to be weighted for retrieval features through preliminary ranking results, without involving more complex network optimization processes. Is my understanding correct? Is β among them learnable?

![image](https://github.com/ShihaoShao-GH/SuperGlobal/assets/83576010/34574462-c5d0-4a9e-9fb5-11c7c9580c03)
R

**Comment by yejy53** [comment]
I understand the beta settings! But what I don't know is that gi is implemented by calculating distances between database features?

**Comment by ShihaoShao-GH** [comment]
Hi. Thanks for liking our work! $g_*$'s across this paper denote the global features of given images. The similarities between g's are determined by the dot product with the vectors g's being of unit length.

**Comment by yejy53** [comment]
Thank you for your excellent work. I still don’t understand it. It seems that your reordering network does not require training and has no corresponding loss.

**Comment by darthvaddor** [comment]
> Thank you for your excellent work. I still don’t understand it. It seems that your reordering network does not require training and has no corresponding loss.

Hey I'm trying to use the reranking network alone. How did you do it? I'm using a vector database retrieval system how do I integrate that with their reranking network
