### ISSUE TITLE
about DELG-pytouch 

### ISSUE THREAD

**Issue by zyh778** [ShihaoShao-GH/SuperGlobal#14]
Hi, I'm really sorry, after I read your paper and your open source code, I want to use the main framework of DELG-pytouch, and use the pooling method in your paper plus some of my own ideas to improve it, but after I download DELG's project and configure the environment according to his readme, I can't run it according to the steps he said. to run it, and then thought that you have run that code, so I would like to ask if the code you ran through is still there, or have you ever encountered a problem with not finding val_list.txt or any other problem that

**Comment by ShihaoShao-GH** [comment]
No worries. Do you have a WeChat account or something like that? I can send you mine.

**Comment by zyh778** [comment]
感谢您的回信，也感谢您能提供帮助，18101085910这是我的微信账号


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShihaoShao-GH/SuperGlobal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月18日(星期四) 中午12:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShihaoShao-GH/SuperGlobal] about DELG-pytouch  (Issue #14)





 
No worries. Do you have a WeChat account or something like that? I can send you mine.

**Comment by zyh778** [comment]
Thank you and if_then_668 is my WeChat account.
