### ISSUE TITLE
Understand the reordering network

### ISSUE THREAD

**Issue by yejy53** [ShihaoShao-GH/SuperGlobal#15]
Hello, thank you for your excellent work, but I don’t quite understand the reordering network. Why should I choose max pooling and average pooling to refine features? What is its theoretical basis? Can you give some non-experimental explanations of interpretability?

**Comment by yejy53** [comment]
There are still some method details that I don’t know very well. Can I use WeChat to communicate? My account: y18300084937

**Comment by ShihaoShao-GH** [comment]
Sorry for the delay. I just reached you out at Wechat:)

**Comment by J-A-Varsha** [comment]
> Hello, thank you for your excellent work, but I don’t quite understand the reordering network. Why should I choose max pooling and average pooling to refine features? What is its theoretical basis? Can you give some non-experimental explanations of interpretability?

Hey if you were able to figure out the reranking network please explain
