### ISSUE TITLE
how to train model on my own data

### ISSUE THREAD

**Issue by rsqai** [ShihaoShao-GH/SuperGlobal#2]
how to train model on my own data

**Comment by ShihaoShao-GH** [comment]
So first, SuperGlobal don't need training, and if you want to apply it to your own model, then just directly plug in your desired modules (e.g., GeM+, Regional-GeM, Reranking, etc,.) to your any trained model. To maximize the performance, a grid search is suggested to tune the parameter p (and it costs very less time as stated in the paper).
