### ISSUE TITLE
Issue Replicating SuperGlobal Results: "Override list has odd length" Error

### ISSUE THREAD

**Issue by hkhk368** [ShihaoShao-GH/SuperGlobal#6]
Dear authors,

I recently came across your paper on SuperGlobal and found it to be particularly insightful. In addition, I have also familiarized myself with the contents of CVNET.

For CVNET, I was able to successfully execute the following command without any issues:
`python test.py MODEL.DEPTH 50 TEST.WEIGHTS CVPR2022_CVNet_R50.pyth TEST.DATA_DIR ./revisitop/data/datasets 
`
However, when attempting to replicate the results for SuperGlobal using the following command, I encountered an error suggesting an odd length for the parameter list. I would greatly appreciate your guidance in resolving this matter.
`python test.py MODEL.DEPTH 50 TEST.WEIGHTS ./weights/CVPR2022_CVNet_R50.pyth TEST.DATA_DIR ./revisitop/data/datasets SupG.gemp SupG.rgem SupG.sgem SupG.relup SupG.rerank SupG.onemeval False`
Below is the traceback for your reference:
`Traceback (most recent call last):
  File "D:\test\github\SuperGlobal\test.py", line 17, in <module>
    main()
  File "D:\test\github\SuperGlobal\test.py", line 10, in main
    config.load_cfg_fom_args("test a CVNet model.")
  File "D:\test\github\SuperGlobal\config.py", line 145, in load_cfg_fom_args
    _C.merge_from_list(args.opts)
  File "C:\Users\u\.conda\envs\test\Lib\site-packages\yacs\config.py", line 223, in merge_from_list
    _assert_with_logging(
  File "C:\Users\u\.conda\envs\test\Lib\site-packages\yacs\config.py", line 545, in _assert_with_logging
    assert cond, msg
AssertionError: Override list has odd length: ['MODEL.DEPTH', '50', 'TEST.WEIGHTS', './weights/CVPR2022_CVNet_R50.pyth', 'TEST.DATA_DIR', './revisitop/data/datasets', 'SupG.gemp', 'SupG.rgem', 'SupG.sgem', 'SupG.relup', 'SupG.rerank', 'SupG.onemeval', 'False']; it must be a list of pairs`
Thank you in advance for your assistance.

**Comment by ShihaoShao-GH** [comment]
Change `['MODEL.DEPTH', '50', 'TEST.WEIGHTS', './weights/CVPR2022_CVNet_R50.pyth', 'TEST.DATA_DIR', './revisitop/data/datasets', 'SupG.gemp', 'SupG.rgem', 'SupG.sgem', 'SupG.relup', 'SupG.rerank', 'SupG.onemeval', 'False']` to `['MODEL.DEPTH', '50', 'TEST.WEIGHTS', './weights/CVPR2022_CVNet_R50.pyth', 'TEST.DATA_DIR', './revisitop/data/datasets', 'SupG.gemp', 'True', 'SupG.rgem', 'True', 'SupG.sgem', 'True', 'SupG.relup', 'True', 'SupG.rerank', 'True', 'SupG.onemeval', 'False']`. 
Please let me know if it works.

**Comment by hkhk368** [comment]
Thanks for your help. It works well.
