### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by UTimeStrange** [ShihaoShao-GH/SuperGlobal#7]
请问下，这个Oxford+1M Hard数据集，是根据  https://github.com/filipradenovic/revisitop  这个生成的是吧。好像原生的数据集只有Oxford 5k 和 Paris 6k这两个，其他的数据集都是造出来的。但是这两个好像都不让下载.
<img width="937" alt="pic1" src="https://github.com/ShihaoShao-GH/SuperGlobal/assets/38728194/5d54ba23-4382-4c7b-84bd-f65b87c8c79d">

还有一个问题想问下，如果我没理解错的话，这个数据集是带有监督标签的, 大家的网络模型都在这个数据集上训练。但是现实场景中，图片数据集通常是没有标签的，只是做一个相似度召回系统，是否有考虑到这种情况。这样的话很多模型结构都不成立了，因为没法训练。

**Comment by ShihaoShao-GH** [comment]
> 请问下，这个Oxford+1M Hard数据集，是根据 https://github.com/filipradenovic/revisitop 这个生成的是吧。好像原生的数据集只有Oxford 5k 和 Paris 6k这两个，其他的数据集都是造出来的。但是这两个好像都不让下载.

You can ask the author of https://github.com/filipradenovic/revisitop for downloading the dataset. 

> 还有一个问题想问下，如果我没理解错的话，这个数据集是带有监督标签的, 大家的网络模型都在这个数据集上训练。但是现实场景中，图片数据集通常是没有标签的，只是做一个相似度召回系统，是否有考虑到这种情况。这样的话很多模型结构都不成立了，因为没法训练。

From your idea, any of the supervised computer vision task is non-sense, including the classification task on ImageNet. 

Basically, when you train on _similar_ domain then infer on another, such supervised training (with certain limitation) can work which does not require you train on the exact same doamin. Back to this task, a model trained on GLDv2, is enough for predicting the similarities in a boarder range of queries and indexes, only if it is also for landmarks (the best case).

If you still insist on the useless of supervised learning, then I recommend you to dive into un-, semi-, or weakly-supervised learning. If you want to boost the inference performance upon the basis of limiting supervised learning, then domain adaption is for you.

Thank you for raising this question. I always feel like such conversation is helpful.
